name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install coverage
        pip install git+https://github.com/majamassarini/knx-stack.git@dev
        pip install git+https://github.com/majamassarini/automate-home.git

    - name: Run unit tests with coverage
      run: |
        coverage run -m unittest discover -v
        coverage report -m
        coverage xml

    - name: Run doctests
      run: |
        python -m doctest knx_plugin/gateway/knxnet_ip.py -v || true
        python -m doctest knx_plugin/message.py -v || true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
